# Generated by Django 5.2.17 on 2026-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_workers',
            field=models.ManyToManyField(blank=True, related_name='active_tasks', to='tasks.person'),
        ),
    ]
